#!/usr/bin/env python
# -*- coding: UTF-8 -*-

'''
Creado el 22/1/2015

@author:  Aldrix Marfil     10-10940
@author:  Leonardo Martinez 11-10576
'''

import parser
import sys

if __name__ == '__main__':
    
    #Comprobacion de los parametros de entrada. 
    if len(sys.argv) != 2:
        print "Error: Parametros de entrada incorrectos."
        exit()

    #Abrimos el archivo del codigo setlan
    codeFile = open(sys.argv[1], 'r')
    code = codeFile.read()
    
    #Ejecutamos el Parser
    arbol = parser.build_parser(code)


    #Impresion en pantalla del primer error del Lexer
    #(si hay alguno). 
    if parser.lexer_errorList != []:
        print parser.lexer_errorList[0]
    else: 
        #Impresion en pantalla del primer error del Parser 
        #(si hay alguno). 
        if parser.parser_errorList != []:
            print parser.parser_errorList[0]

        else:
            print arbol.printTree(0)