#!/usr/bin/env python
# -*- coding: UTF-8 -*-

############################
#  Proyecto I - CI3725     #
#  Grupo 2                 #
#  Luis Colorado 09-11086  #
#  Nicolas Manan 06-39883  #
############################

import parser


def main(argv=None):
    import sys      # argv, exit

    if argv is None:
        argv = sys.argv

    if len(argv) == 1:
        print "ERROR: No se encuentra el archivo"
        return
    elif len(argv) > 2:
        print "ERROR: Numero invalido de argumentos"
        return

    try:
        # Opens and reads file to interpret
        file_string = open(argv[1], 'r').read()
    except IOError:
        print "ERROR: Must give an input file"
        return

    #print "pasando el lexer"
    #lexer_tokenList = parser.lexing(file_string)
    #for token in lexer_tokenList:
    #   print token

    ast = parser.parsing(file_string)

    # Check for Overflow or Unexpected character errors
    if parser.lexer_error:
        ast = None
        for error in parser.lexer_error:
            print error
    elif parser.parser_error:
        ast = None
        for error in parser.parser_error:
            print error
    else:
        print ast


if __name__ == "__main__":
    main()
