#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

## Interpretador del lenguaje Setlan.
## Programa principal, Etapa 2.
## Autores:  - Mónica Figuera   11-10328
##           - Carlos Spaggiari 11-10987

import  sys
from    lexer  import *
from    parser import *

def main():
    if len(sys.argv) == 1:
        print "ERROR: Debe introducir el nombre de un archivo."
        exit(1)
    elif len(sys.argv) > 2:
        print "ERROR: Número inválido de argumentos."
        exit(1)

    try:
        data = open(sys.argv[1])
    except:
        print "ERROR: El archivo '%s' no existe." % (sys.argv[1])
        exit(1)

    arbol = parser.parse(data.read())

    if lexError != []:
        for error in lexError:
            print error
        exit(1)
    else:
        if yaccError != []:
            print yaccError[0]
            exit(1)
        else:
            print arbol.printTree(0)

if __name__ == "__main__":
    main()