#!/usr/bin/env python

import sys
import Lexer
import Parser

def main():

	# Construimos el Lexer 
	if (len(sys.argv) > 1):
		Lexer.scanner(sys.argv[1],False)
		Parser.analizador_sintactico(sys.argv[1])
	else:
		print "Verifique que la sintaxis introducida es correcta."
		print "./setlan <nombre del archivo>\n"


if __name__ == "__main__":
	main()


# END setlan.py
