#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
Interpreter for RangeX Language
CI3725 - Entrega 3 Grupo 7.
Alberto Cols, 09-10177
Matteo Ferrando, 09-10285
"""

import Parser


def main(argv=None):
    import sys      # argv

    if argv is None:
        argv = sys.argv

    if len(argv) == 1:
        print "ERROR: No input file"
        return
    elif len(argv) > 2:
        print "ERROR: Invalid number of arguments"
        return

    try:
        # Opens and reads file to interpret
        file_string = open(argv[1], 'r').read()
    except IOError:
        print "ERROR: Must give an input file"
        return

    ast = Parser.parsing(file_string)

    # Check for Overflow or Unexpected character errors
    if Parser.lexer_error:
        for error in Parser.lexer_error:
            print error

    # Check for Syntax errors
    elif Parser.parser_error:
        for error in Parser.parser_error:
            print error

    # Check for Static errors
    elif Parser.static_error:
        for error in Parser.static_error:
            print error

    else:
        print ast

    return ast


if __name__ == "__main__":
    main()
