#! /usr/bin/env python
# -*- coding: utf-8 -*-

# # # # # # # # # # # # # # # # # # # # # # # #
#	TRADUCTORES E INTERPRETADORES CI3725      #
#	Segunda entrega del proyecto.             #
#	Autores: Carlos Martínez 	- 11-10584    #
#			 Christian Teixeira - 11-11016    #
# # # # # # # # # # # # # # # # # # # # # # # #

import sl_lexer, sl_parser

# main del programa

def getcol(lineas, token, number_lines=0):
	aux = 0
	for i in range(token.lineno-number_lines-1):
		aux = aux + len(lineas[i])
	return str(token.lexpos - aux + 1)

def main(argv  = None):
	import sys
	if(argv is None):
		argv = sys.argv
	if(len(argv) == 1):
		print("ERROR: No se encontró argumento.\nUso: ./setlan [Nombre_Archivo]\nPor favor verifíque que el archivo existe en su directorio y está correctamente escrito.")
		exit(1)
	else:
		if str(argv[1])[-4:] != ".stl":
			print("ERROR: No se reconoce el formato del archivo.\n")
			exit(1) 

	global error_lex
	global error_par
	error_lex = []
	error_par = []
	out = []

	nombreArchivo = argv[1]
	archivo = open(nombreArchivo, "r")
	lineas = archivo.readlines()
	archivo.seek(0)
	contenido = archivo.read()

	lexer = sl_lexer.build_lexer(contenido)
	error_lex = sl_lexer.get_errors()

	# Loop para extraer tokens correctos

	while True:
		tok = lexer.token()
		if not tok: break
		out.append(tok)		# Se incluyen en la lista de out

	# # Imprimir resultados

	number_lines = 0			# Numero de lineas del archivo para reiniciar el contador lineno en el parser
	if len(error_lex) != 0:		# Lista de error del lexer no vacía, se imprimen solo los tokens de error encontrados
		for t in error_lex:
			print("Error: Se encontró un caracter inesperado \"" + t.value[0] + "\" en la Línea " + str(t.lineno) + ", Columna " + getcol(lineas, t) + ".")
			number_lines = t.lineno
		exit(0)
	else:
		number_lines = out[-1].lineno

	parser = sl_parser.build_parser()
	AST = parser.parse(contenido)
	if sl_parser.get_errors(): error_par = sl_parser.get_errors()
	if len(error_par) != 0:		# Lista de error del parser no vacia, se imprime solo el primer token de error de sintaxis encontrado
		p = error_par[0]
		print("Error de sintaxis: Token '" + str(p.value) + "' inesperado en línea " + str(p.lineno - number_lines) + ", columna " + getcol(lineas, p, number_lines) + ".")
	if AST:
		print(AST)


if __name__ == "__main__":
	main()