#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

## Interpretador del lenguaje Setlan.
## Programa principal.
## Autores:  - Mónica Figuera   11-10328
##           - Carlos Spaggiari 11-10987

import  sys
import  re
from    lexer   import *
from    parser  import *
from    AST     import *

def main():
    if len(sys.argv) < 1:
        print "ERROR: Debe introducir el nombre de un archivo."
        exit(1)
    elif len(sys.argv) > 5 or len(sys.argv) < 2:
        print "ERROR: Número inválido de argumentos."
        exit(1)

    for i in range(2,len(sys.argv)):
        if not re.match(r'^-[t|a|s]$',sys.argv[i]):
            print "ERROR: '%s' es un flag inválido." % (sys.argv[i])
            exit(1)

    try:
        data = open(sys.argv[1])
    except:
        print "ERROR: El archivo '%s' no existe." % (sys.argv[1])
        exit(1)

    arbol = parser.parse(data.read())                       # LEXER, PARSER

    if lexError != []:
        for error in lexError:
            print error
        exit(1)
    else:
        if yaccError != []:
            print yaccError[0]
            exit(1)
        else:
            if arbol.checkType():                            # CHEQUEO ESTÁTICO Y DINÁMICO
                for i in range(2,len(sys.argv)):
                    if sys.argv[i] == "-a":
                        print arbol.printTree(0)

                    elif sys.argv[i] == "-s":    
                        print arbol.scope
                    
                    elif sys.argv[i] == "-t":
                        printLex(open(sys.argv[1]).read())
                arbol.evaluate()

if __name__ == "__main__":
    main()